version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/ekar-assignment?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - ekar-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "3307:3306"
    networks:
      - ekar-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ekar-assignment
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    volumes:
      - db:/var/lib/mysql

networks:
  ekar-net:
volumes:
  db: